# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-23 05:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(default='', max_length=2000)),
                ('question_type', models.CharField(choices=[('MULTI_SELECT', 'Multi Select'), ('MULTI_CHOICE', 'Multi Choice')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='quiz/images')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=2000)),
                ('duration', models.IntegerField()),
                ('questions', models.ManyToManyField(to='quiz.Question')),
            ],
            options={
                'verbose_name': 'Quiz',
                'verbose_name_plural': 'Quizs',
            },
        ),
        migrations.CreateModel(
            name='QuizHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('duration', models.IntegerField()),
                ('completed_on', models.DateTimeField(blank=True, null=True)),
                ('is_timedout', models.BooleanField(default=False)),
                ('mark', models.IntegerField(default=0)),
                ('completed_in_secs', models.IntegerField(blank=True, null=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizheader_quiz', to='quiz.Quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizheader_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'QuizHeader',
                'verbose_name_plural': 'QuizHeaders',
            },
        ),
        migrations.CreateModel(
            name='QuizHeaderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_answered', models.BooleanField(default=False)),
                ('is_skipped', models.BooleanField(default=False)),
                ('position', models.IntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizheaderdetail_question', to='quiz.Question')),
                ('quiz_header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizheaderdetail_quizheader', to='quiz.QuizHeader')),
            ],
            options={
                'verbose_name': 'QuizHeaderDetail',
                'verbose_name_plural': 'QuizHeaderDetails',
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_text', models.CharField(max_length=255)),
                ('is_correct_response', models.BooleanField(default=False)),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='response_question', to='quiz.Question')),
            ],
            options={
                'verbose_name': 'Response',
                'verbose_name_plural': 'Responses',
            },
        ),
        migrations.AddField(
            model_name='quizheaderdetail',
            name='response',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizheaderdetail_response', to='quiz.Response'),
        ),
    ]
